name: Build Container with Buildah

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build container image
        run: buildah bud --squash --format docker -t timpi-collector -f oci/Containerfile .

      - name: Set container version
        run: |
          [[ -f "update_version.txt" ]]; then
            echo "IMAGE_TAG=$(awk -F ':' '{ print $1 }' < update_version.txt)" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=$(awk -F ':' '{ print $1 }' < major_version.txt)" >> $GITHUB_ENV
          fi

      - name: Push image to GitHub Container Registry
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          buildah push timpi-collector ghcr.io/${{ github.repository }}/timpi-collector:${{ env.IMAGE_TAG }}
